package Vista;

import Modelo.Datos;
import Modelo.Usuario;
import static Controlador.ArchivosUsuarios.*;
import java.awt.Color;
import java.io.IOException;
import javax.swing.JOptionPane;

public class Registro extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registro.class.getName());

    //CONSTRUCTOR
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        botonIngreso = new javax.swing.JButton();
        botonRegistro = new javax.swing.JButton();
        labelApellido = new javax.swing.JLabel();
        labelCombo = new javax.swing.JLabel();
        textApellido = new javax.swing.JTextField();
        textCorreo = new javax.swing.JTextField();
        labelNombre = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        combobox = new javax.swing.JComboBox<>();
        labelCorreo = new javax.swing.JLabel();
        labelCedula = new javax.swing.JLabel();
        textCedula = new javax.swing.JTextField();
        labelClave = new javax.swing.JLabel();
        labelRetry = new javax.swing.JLabel();
        botonPane = new javax.swing.JPanel();
        labelBotonpane = new javax.swing.JLabel();
        passretry = new javax.swing.JPasswordField();
        passfield = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro");
        setLocationByPlatform(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitulo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Registrarse");
        bg.add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        botonIngreso.setBackground(new java.awt.Color(204, 204, 204));
        botonIngreso.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        botonIngreso.setForeground(new java.awt.Color(102, 102, 102));
        botonIngreso.setText("Ingresar");
        botonIngreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonIngresoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonIngresoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonIngresoMouseExited(evt);
            }
        });
        botonIngreso.addActionListener(this::botonIngresoActionPerformed);
        bg.add(botonIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 120, 30));

        botonRegistro.setBackground(new java.awt.Color(0, 153, 51));
        botonRegistro.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        botonRegistro.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistro.setText("Registrarse");
        botonRegistro.addActionListener(this::botonRegistroActionPerformed);
        bg.add(botonRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 120, 30));

        labelApellido.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelApellido.setForeground(new java.awt.Color(102, 102, 102));
        labelApellido.setText("Apellido");
        bg.add(labelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        labelCombo.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelCombo.setForeground(new java.awt.Color(102, 102, 102));
        labelCombo.setText("Tipo de usuario");
        bg.add(labelCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        textApellido.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        bg.add(textApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 140, -1));

        textCorreo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        bg.add(textCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 210, -1));

        labelNombre.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(102, 102, 102));
        labelNombre.setText("Nombre");
        bg.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 20));

        textNombre.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        bg.add(textNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 140, -1));

        combobox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Estudiante", "Empleado", "Profesor", "Administrador" }));
        combobox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        combobox.addActionListener(this::comboboxActionPerformed);
        bg.add(combobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 140, -1));

        labelCorreo.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelCorreo.setForeground(new java.awt.Color(102, 102, 102));
        labelCorreo.setText("Correo");
        bg.add(labelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        labelCedula.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelCedula.setForeground(new java.awt.Color(102, 102, 102));
        labelCedula.setText("Cedula");
        bg.add(labelCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        textCedula.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        bg.add(textCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 140, -1));

        labelClave.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelClave.setForeground(new java.awt.Color(102, 102, 102));
        labelClave.setText("Contraseña");
        bg.add(labelClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        labelRetry.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelRetry.setForeground(new java.awt.Color(102, 102, 102));
        labelRetry.setText("Confirmar Contraseña");
        bg.add(labelRetry, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        labelBotonpane.setBackground(new java.awt.Color(204, 204, 204));
        labelBotonpane.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        labelBotonpane.setForeground(new java.awt.Color(102, 102, 102));
        labelBotonpane.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBotonpane.setText("Crear Cuenta");
        labelBotonpane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelBotonpane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBotonpaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelBotonpaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelBotonpaneMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botonPaneLayout = new javax.swing.GroupLayout(botonPane);
        botonPane.setLayout(botonPaneLayout);
        botonPaneLayout.setHorizontalGroup(
            botonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBotonpane, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
        );
        botonPaneLayout.setVerticalGroup(
            botonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBotonpane, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        bg.add(botonPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, 50));

        passretry.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        passretry.setForeground(new java.awt.Color(153, 153, 153));
        passretry.setText("********");
        passretry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passretryMousePressed(evt);
            }
        });
        bg.add(passretry, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 210, -1));

        passfield.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        passfield.setForeground(new java.awt.Color(153, 153, 153));
        passfield.setText("********");
        passfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passfieldMousePressed(evt);
            }
        });
        passfield.addActionListener(this::passfieldActionPerformed);
        bg.add(passfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 210, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIngresoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIngresoMouseEntered
        botonIngreso.setBackground(new Color(0,153,51));
        botonIngreso.setForeground(Color.white);
        botonRegistro.setBackground(new Color(204,204,204));
        botonRegistro.setForeground(Color.gray);
    }//GEN-LAST:event_botonIngresoMouseEntered

    private void botonIngresoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIngresoMouseExited
        botonRegistro.setBackground(new Color(0,153,51));
        botonRegistro.setForeground(Color.white);
        botonIngreso.setBackground(new Color(204,204,204));
        botonIngreso.setForeground(Color.gray);
    }//GEN-LAST:event_botonIngresoMouseExited

    private void labelBotonpaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBotonpaneMouseEntered
        labelBotonpane.setForeground(Color.white);
        botonPane.setBackground(new Color(0,153,51));
    }//GEN-LAST:event_labelBotonpaneMouseEntered

    private void labelBotonpaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBotonpaneMouseExited
        labelBotonpane.setForeground(Color.gray);
        botonPane.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_labelBotonpaneMouseExited

    private void botonIngresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIngresoMouseClicked
        //REDIRIGIR A LA INTERFAZ DE LOGIN
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
        this.setVisible(false);
    }//GEN-LAST:event_botonIngresoMouseClicked

    private void labelBotonpaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBotonpaneMouseClicked
        //REDIRIGIR A INTERFAZ DE LOGIN POR MEDIO DEL REGISTRO
        
        //VALIDACION POR CAMPOS VACIOS
        if(textNombre.getText().equals("")   || 
           textApellido.getText().equals("") || 
           textCedula.getText().equals("")   || 
           textCorreo.getText().equals("")   ||  
           String.valueOf(passfield.getPassword()).equals("") || 
           String.valueOf(passretry.getPassword()).equals("") ||
           combobox.getSelectedItem().equals("")){
        JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");
        }
        //VALIDACION DE NOMBRE Y APELLIDO QUE NO CONTENGAN NUMEROS
        if(!textNombre.getText().matches(".*[a-zA-Z].*") || !textApellido.getText().matches(".*[a-zA-Z].*")){
        JOptionPane.showMessageDialog(null,"Nombres y Apellidos no pueden contener");
        }
        //VALIDACION DE QUE LA CEDULA SOLO CONTENGA NUMEROS VERIFICANDO LA EXISTENCIA DE ALGUNA LETRA 
        if(textCedula.getText().trim().matches(".*[a-zA-Z].*") || textCedula.getText().contains(" ")){
            JOptionPane.showMessageDialog(null,"La cedula no puede contener letras o espaciadores ");
            textCedula.setText("");
        }
        //VALIDACION DE QUE LA CEDULA NO EMPIECE POR 0 CORTANDO LA CADENA EN LA PRIMERA POSICION
        if(textCedula.getText().substring(0,1).equals("0")){
            JOptionPane.showMessageDialog(null, "La cedula no puede empezar con 0");
        }
        //VALIDACION DE QUE LA CEDULA NO SOBREPASE LOS 9 DIGITOS
        if(textCedula.getText().length() >= 9){
        JOptionPane.showMessageDialog(null,"La cedula no puede tener mas de 9 digitos");
        }
         //VALIDACION POR ESPACIOS EN LA CONTRASEÑA
         if(String.valueOf(passfield.getPassword()).contains(" ") ||
           String.valueOf(passretry.getPassword()).contains(" ")){
        JOptionPane.showMessageDialog(null,"La contraseña no puede contener espacios");
        }
        //VALIDACION POR LIMITE DE CARACTERES EN LA CONTRASEÑA
        if(String.valueOf(passfield.getPassword()).length() > 15 || 
           String.valueOf(passretry.getPassword()).length() > 15){
                JOptionPane.showMessageDialog(null,"La contraseña no puede tener mas de 16 caracteres");
        }     
        //VALIDACION POR CORREO Y PODER PASAR AL REGISTRO
        if(!textCorreo.getText().contains("@") || !textCorreo.getText().contains(".com")){
            JOptionPane.showMessageDialog(null,"El correo debe contener '@' y '.com' ");
        }else{
            //VALIDACION ADICIONAL DE QUE EL CORREO SEA EXISTENTE
            if(textCorreo.getText().contains("gmail") || textCorreo.getText().contains("hotmail")
              || textCorreo.getText().contains("outlook") || textCorreo.getText().contains("yahoo"))
            {
                //SI LA CONFIRMACION DE CLAVE ES CORRECTA SE PASA A CARGAR EN LA DATABASE
                if(String.valueOf(passfield.getPassword()).equals(String.valueOf(passretry.getPassword())) ){
                    //SE CREA UNA INSTANCIA DE UN USUARIO
                         Usuario persona = new Usuario(textNombre.getText(),textApellido.getText(),
                         textCorreo.getText(), String.valueOf(passfield.getPassword()),
                        textCedula.getText(), String.valueOf(combobox.getSelectedItem()));
                    //SE CREA UN ARCHIVO DE LOS DATOS
                        Datos archivo = new Datos();
                    //VALIDACION DE QUE EL USUARIO YA SE ENCUENTRE REGISTRADO
                         if(validarUsuarioEnRegistro(archivo.getUsers(),persona)){
                             JOptionPane.showMessageDialog(null,"Este usuario ya existe");
                         }else{
                         //SI NO EXISTE EL USUARIO ENTONCES SE CREA
                         try {
                                    agregarUsuarioArchivo(archivo.getUsers(),persona);
                             } catch (IOException ex) {
                                 System.getLogger(Registro.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                             }
                             JOptionPane.showMessageDialog(null,"Su cuenta ha sido creada con exito");
                         }
                }else{
                //DE LO CONTRARIO SE LANZA UN AVISO
                JOptionPane.showMessageDialog(null,"Las contraseñas no son iguales");
                }
            }else{
                JOptionPane.showMessageDialog(null,"El correo no es valido");
            }             
    }//GEN-LAST:event_labelBotonpaneMouseClicked
    }
    
    private void passfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passfieldActionPerformed

    private void passfieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passfieldMousePressed
        //CUANDO EL ESPACIO DE CONTRASEÑAS ES PRESIONADO SE LIMPIA
        if(String.valueOf(passfield.getPassword()).equals("********")){
        passfield.setText("");
        }
    }//GEN-LAST:event_passfieldMousePressed

    private void passretryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passretryMousePressed
        //CUANDO EL ESPACIO DE CONTRASEÑAS ES PRESIONADO SE LIMPIA
    if(String.valueOf(passretry.getPassword()).equals("********")){
    passretry.setText("");
    }//GEN-LAST:event_passretryMousePressed
   }
    private void botonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegistroActionPerformed

    private void botonIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonIngresoActionPerformed

    private void comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        java.awt.EventQueue.invokeLater(() -> new Registro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton botonIngreso;
    private javax.swing.JPanel botonPane;
    private javax.swing.JButton botonRegistro;
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelBotonpane;
    private javax.swing.JLabel labelCedula;
    private javax.swing.JLabel labelClave;
    private javax.swing.JLabel labelCombo;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelRetry;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPasswordField passfield;
    private javax.swing.JPasswordField passretry;
    private javax.swing.JTextField textApellido;
    private javax.swing.JTextField textCedula;
    private javax.swing.JTextField textCorreo;
    private javax.swing.JTextField textNombre;
    // End of variables declaration//GEN-END:variables

    private Color Font(String calibri, int i, int i0) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
